    drop table if exists ss_post;

    drop table if exists ss_role;

    drop table if exists ss_user;

    drop table if exists ss_user_role;
    
    drop table if exists ss_log;

    create table ss_post (
        dtype varchar(31) not null,
        id bigint generated by default as identity,
        content clob,
        modify_time timestamp,
        title varchar(255) not null,
        user_id bigint,
        subject_id bigint,
        primary key (id)
    );

    create table ss_role (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table ss_user (
        id bigint generated by default as identity,
        create_by varchar(255),
        create_time timestamp,
        last_modify_by varchar(255),
        last_modify_time timestamp,
        email varchar(255),
        login_name varchar(255) not null unique,
        name varchar(255),
        plain_password varchar(255),
        sha_password varchar(255),
        status varchar(255),
        version integer,
        primary key (id)
    );

    create table ss_user_role (
        user_id bigint not null,
        role_id bigint not null,
        primary key (user_id, role_id)
    );
    
    create table ss_log (
    	THREAD_NAME varchar(255),
    	LOGGER_NAME varchar(255),
    	TIMESTAMP timestamp,
    	LEVEL varchar(20),
    	MESSAGE varchar(255)
    );

    alter table ss_post 
        add constraint FK8D193F1F7334D076 
        foreign key (subject_id) 
        references ss_post;

    alter table ss_post 
        add constraint FK8D193F1FF125651E 
        foreign key (user_id) 
        references ss_user;

    alter table ss_user_role 
        add constraint FK1306854BF125651E 
        foreign key (user_id) 
        references ss_user;

    alter table ss_user_role 
        add constraint FK1306854B4BFAA13E 
        foreign key (role_id) 
        references ss_role;
