drop table SS_LOG;
drop table SS_POST;
drop table SS_USER_ROLE;
drop table SS_USER;
drop table SS_ROLE;

create table SS_USER (
ID integer primary key GENERATED BY DEFAULT as IDENTITY (START WITH 1000, INCREMENT BY 1),
LOGIN_NAME varchar(20) not null unique,
PASSWORD varchar(20),
NAME varchar(20),
EMAIL varchar(30),
STATUS varchar(30),
VERSION integer,
CREATE_TIME timestamp,
CREATE_BY varchar(20),
LAST_MODIFY_TIME timestamp,
LAST_MODIFY_BY varchar(20)
);
create unique index SS_USER_LOGIN_NAME_INDEX on SS_USER(LOGIN_NAME);

create table SS_ROLE (
ID integer primary key GENERATED BY DEFAULT as IDENTITY (START WITH 1000, INCREMENT BY 1),
NAME varchar(20) not null unique
);

create table SS_USER_ROLE (
USER_ID integer not null,
ROLE_ID integer not null,
FOREIGN KEY (ROLE_ID) references SS_ROLE(ID),
FOREIGN KEY (USER_ID) references SS_USER(ID)
);

create table SS_POST (
ID integer primary key GENERATED BY DEFAULT as IDENTITY (START WITH 1000, INCREMENT BY 1),
DTYPE varchar(10) not null,
TITLE varchar(100) not null,
CONTENT clob not null,
USER_ID integer not null,
SUBJECT_ID integer,
MODIFY_TIME timestamp,
FOREIGN KEY (USER_ID) references SS_USER(ID)
);

create table SS_LOG (
THREAD_NAME varchar(255),
LOGGER_NAME varchar(255),
TIMESTAMP timestamp,
LEVEL varchar(20),
MESSAGE varchar(255)
);