drop table LOGS;
drop table POSTS;
drop table USERS_ROLES;
drop table USERS;
drop table ROLES;

create table USERS (
ID integer primary key GENERATED BY DEFAULT as IDENTITY,
LOGIN_NAME varchar(20) not null unique,
PASSWORD varchar(20),
NAME varchar(20),
EMAIL varchar(30),
STATUS varchar(30),
VERSION integer,
CREATE_TIME timestamp,
CREATE_BY varchar(20),
LAST_MODIFY_TIME timestamp,
LAST_MODIFY_BY varchar(20)
);
create unique index USERS_LOGIN_NAME_INDEX on USERS(LOGIN_NAME);

create table ROLES (
ID integer primary key GENERATED BY DEFAULT as IDENTITY,
NAME varchar(20) not null unique
);

create table USERS_ROLES (
USER_ID integer not null,
ROLE_ID integer not null,
FOREIGN KEY (ROLE_ID) references ROLES(ID),
FOREIGN KEY (USER_ID) references USERS(ID)
);

create table POSTS (
ID integer primary key GENERATED BY DEFAULT as IDENTITY,
DTYPE varchar(10) not null,
TITLE varchar(100) not null,
CONTENT clob not null,
USER_ID integer not null,
FOREIGN KEY (USER_ID) references USERS(ID)
);

create table LOGS (
THREAD_NAME varchar(255),
LOGGER_NAME varchar(255),
TIMESTAMP timestamp,
LEVEL varchar(20),
MESSAGE varchar(255)
);