
    alter table acct_user_role 
        drop constraint FKFE85CB3E16A0ABF1;

    alter table acct_user_role 
        drop constraint FKFE85CB3E7175E811;

    drop table acct_role if exists;

    drop table acct_user if exists;

    drop table acct_user_role if exists;

    create table acct_role (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table acct_user (
        id bigint generated by default as identity,
        email varchar(255),
        login_name varchar(255) not null unique,
        name varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table acct_user_role (
        user_id bigint not null,
        role_id bigint not null
    );

    alter table acct_user_role 
        add constraint FKFE85CB3E16A0ABF1 
        foreign key (user_id) 
        references acct_user;

    alter table acct_user_role 
        add constraint FKFE85CB3E7175E811 
        foreign key (role_id) 
        references acct_role;
